### PR TITLE
Add guide for add-ons and env vars

### PR DESCRIPTION
**Pull request by marcelkooi**
Adds a guide for add-ons and environment variables

### CODE REVIEW

**Comment by marcelkooi** [comment]
@greglobinski Any thoughts on this guide?

**Comment by greglobinski** [comment]
@marcelkooi Sorry for the delay, I will take care of it on the weekend.

**Comment by greglobinski** [comment]
@marcelkooi 
Thank you Marcel and sorry for the delay.

**Comment by marcelkooi** [comment]
@greglobinski No problem!

**Pull request merged**
